spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/eventostec
spring.datasource.username=root
spring.datasource.password=suasenhabarril
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
aws.region=us-east-1
aws.bucket.name=eventostec-imagens123
aws.accessKey=XXXX
aws.secretKey=XXXX
spring.profiles.active=dev